services:
  server:
    build:
      context: .
      dockerfile: ./puck_server/Dockerfile
      target: final
    ports:
      - 50051:50051
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - puck-db-data:/var/lib/postgresql/data
      - ./postgres_db_init.sql:/docker-entrypoint-initdb.d/postgres_db_init.sql
    env_file:
      - .env
    environment:
      - POSTGRES_DB=puck
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  puck-db-data:


