name: puck_client
description: gRPC client for puck_sim
version: 1.0.0
repository: https://github.com/shaynekellyii/puck_sim

environment:
  sdk: ^3.4.0

dependencies:
  grpc: ^3.2.4
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
