include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # freezed: https://pub.dev/packages/freezed#install
    invalid_annotation_target: ignore
    # mobx
    library_private_types_in_public_api: ignore

linter:
  rules:
