name: puck_app
description: 'Flutter app for multiplayer hockey GM game.'
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.5
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.4
  json_annotation: ^4.9.0

  # local
  puck_client:
    path: ../puck_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
